-- V1: Schema inicial do sistema bibliotecario (PostgreSQL)
-- Colunas normalizadas em snake_case. `atrasado` virou boolean (era varchar(1) Y/N no legado).

CREATE TABLE adms
(
    codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login  varchar(15) NOT NULL,
    senha  varchar(60) NOT NULL,
    nome   varchar(20) NOT NULL
);

CREATE TABLE turma
(
    codigo    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao varchar(45) NOT NULL
);

CREATE TABLE aluno
(
    codigo       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_turma integer,
    CONSTRAINT fk_aluno_turma FOREIGN KEY (codigo_turma) REFERENCES turma (codigo)
);

CREATE INDEX idx_aluno_turma ON aluno (codigo_turma);

CREATE TABLE professor
(
    codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE autor
(
    codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   varchar(45)
);

CREATE TABLE cdd
(
    codigo    bigint PRIMARY KEY,
    descricao varchar(45) NOT NULL
);

CREATE TABLE livro
(
    codigo      bigint PRIMARY KEY,
    titulo      varchar(45) NOT NULL,
    qtd         integer,
    codigo_autor integer,
    codigo_cdd  bigint,
    CONSTRAINT fk_livro_autor FOREIGN KEY (codigo_autor) REFERENCES autor (codigo),
    CONSTRAINT fk_livro_cdd FOREIGN KEY (codigo_cdd) REFERENCES cdd (codigo)
);

CREATE INDEX idx_livro_autor ON livro (codigo_autor);
CREATE INDEX idx_livro_cdd ON livro (codigo_cdd);

CREATE TABLE locatario
(
    cpf             varchar(14) PRIMARY KEY,
    nome            varchar(45) NOT NULL,
    telefone        varchar(14),
    codigo_professor integer,
    codigo_aluno    integer,
    CONSTRAINT fk_locatario_professor FOREIGN KEY (codigo_professor) REFERENCES professor (codigo),
    CONSTRAINT fk_locatario_aluno FOREIGN KEY (codigo_aluno) REFERENCES aluno (codigo)
);

CREATE INDEX idx_locatario_professor ON locatario (codigo_professor);
CREATE INDEX idx_locatario_aluno ON locatario (codigo_aluno);

CREATE TABLE loca
(
    codigo               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_livro         bigint      NOT NULL,
    cpf_locatario        varchar(14) NOT NULL,
    data_de_locacao      date        NOT NULL,
    data_para_devolucao  date        NOT NULL,
    atrasado             boolean     NOT NULL,
    CONSTRAINT fk_loca_livro FOREIGN KEY (codigo_livro) REFERENCES livro (codigo),
    CONSTRAINT fk_loca_locatario FOREIGN KEY (cpf_locatario) REFERENCES locatario (cpf)
);

CREATE INDEX idx_loca_livro ON loca (codigo_livro);
CREATE INDEX idx_loca_cpf_locatario ON loca (cpf_locatario);

-- Seed: admin padrao (senha em texto puro, migrada para BCrypt no primeiro login)
INSERT INTO adms (codigo, login, senha, nome)
VALUES (1, '000.000.000-00', 'admin', 'admin');

INSERT INTO turma (codigo, descricao)
VALUES (1, '1º ADM'),
       (2, '1º AGRO'),
       (3, '1º FIN'),
       (4, '1º INF'),
       (5, '2º ADM'),
       (6, '2º AGRO'),
       (7, '2º DCC'),
       (8, '2º FIN'),
       (9, '2º INF'),
       (10, '3º ADM'),
       (11, '3º AGRO'),
       (12, '3º DCC'),
       (13, '3º FIN'),
       (14, '3º INF');

-- Avança as sequences de IDENTITY após inserts com codigo explícito
SELECT setval(pg_get_serial_sequence('adms', 'codigo'), (SELECT max(codigo) FROM adms));
SELECT setval(pg_get_serial_sequence('turma', 'codigo'), (SELECT max(codigo) FROM turma));
