-- V2: Tabela de refresh tokens (opacos, armazenados como SHA-256)
CREATE TABLE refresh_token
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash varchar(64)  NOT NULL,
    adm_id     integer      NOT NULL,
    user_agent varchar(500),
    ip         varchar(45),
    expires_at timestamp    NOT NULL,
    revoked_at timestamp,
    created_at timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_adm FOREIGN KEY (adm_id) REFERENCES adms (codigo)
);

CREATE INDEX idx_refresh_token_adm ON refresh_token (adm_id);
CREATE INDEX idx_refresh_token_expires ON refresh_token (expires_at);
